$(function(){
        $('.cherry').Cherry_Blossoms({
            is_Cherry:true,//是否生成樱花
            image_min:10,//花瓣最小宽度和高度
            image_max:50,//花瓣最大宽度和高度
            time_min:10000,//花瓣最快下坠时间
            time_max:20000,//花瓣最慢下坠时间
            interval:500//花瓣生成时间间隔
        })
    })